enum AchievementTypes {
    oneHundredDaySoloStreak = 'oneHundredDaySoloStreak',
    oneHundredDayChallengeStreak = 'oneHundredDayChallengeStreak',
    oneHundredDayTeamMemberStreak = 'oneHundredDayTeamMemberStreak',
    oneHundredDayTeamStreak = 'oneHundredDayTeamStreak',
    oneHundredCoins = 'oneHundredCoins',
    twoHundredAndFiftyCoins = 'twoHundredAndFiftyCoins',
    fiveHundredCoins = 'fiveHundredCoins',
    oneThousandCoins = 'oneThousandCoins',
    tenThousandCoins = 'tenThousandCoins',
    twentyFiveThousandCoins = 'twentyFiveThousandCoins',
    fiftyThousandCoins = 'fiftyThousandCoins',
    oneHundredThousandCoins = 'oneHundredThousandCoins',
    twoHundredAndFiftyThousandCoins = 'twoHundredAndFiftyThousandCoins',
    fiveHundredThousandCoins = 'fiveHundredThousandCoins',
    oneMillionCoins = 'oneMillionCoins',
    tenTotalTracks = 'tenTotalTracks',
    fiftyTotalTracks = 'fiftyTotalTracks',
    oneHundredTotalTracks = 'oneHundredTotalTracks',
    twoHundredAndFiftyTotalTracks = 'twoHundredAndFiftyTotalTracks',
    fiveHundredTotalTracks = 'fiveHundredTotalTracks',
    oneThousandTotalTracks = 'oneThousandTotalTracks',
}

export default AchievementTypes;
