enum AchievementTypes {
    oneHundredDaySoloStreak = 'oneHundredDaySoloStreak',
    oneHundredDayChallengeStreak = 'oneHundredDayChallengeStreak',
    oneHundredDayTeamMemberStreak = 'oneHundredDayTeamMemberStreak',
    oneHundredDayTeamStreak = 'oneHundredDayTeamStreak',
    oneHundredCoins = 'oneHundredCoins',
    twoHundredAndFiftyCoins = 'twoHundredAndFiftyCoins',
    fiveHundredCoins = 'fiveHundredCoins',
    oneThousandCoins = 'oneThousandCoins',
    tenThousandCoins = 'tenThousandCoins',
    twentyFiveThousandCoins = 'twentyFiveThousandCoins',
    fiftyThousandCoins = 'fiftyThousandCoins',
    oneHundredThousandCoins = 'oneHundredThousandCoins',
    twoHundredAndFiftyThousandCoins = 'twoHundredAndFiftyThousandCoins',
    fiveHundredThousandCoins = 'fiveHundredThousandCoins',
    oneMillionCoins = 'oneMillionCoins',
    tenTotalTimesTracked = 'tenTotalTimesTracked',
    fiftyTotalTimesTracked = 'fiftyTotalTimesTracked',
    oneHundredTotalTimesTracked = 'oneHundredTotalTimesTracked',
    twoHundredAndFiftyTotalTimesTracked = 'twoHundredAndFiftyTotalTimesTracked',
    fiveHundredTotalTimesTracked = 'fiveHundredTotalTimesTracked',
    oneThousandTotalTimesTracked = 'oneThousandTotalTimesTracked',
}

export default AchievementTypes;
