"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var ActivityFeedItemTypes;
(function (ActivityFeedItemTypes) {
    ActivityFeedItemTypes["createdSoloStreak"] = "createdSoloStreak";
    ActivityFeedItemTypes["archivedSoloStreak"] = "archivedSoloStreak";
    ActivityFeedItemTypes["restoredSoloStreak"] = "restoredSoloStreak";
    ActivityFeedItemTypes["deletedSoloStreak"] = "deletedSoloStreak";
    ActivityFeedItemTypes["editedSoloStreakName"] = "editedSoloStreakName";
    ActivityFeedItemTypes["editedSoloStreakDescription"] = "editedSoloStreakDescription";
    ActivityFeedItemTypes["completedSoloStreak"] = "completedSoloStreak";
    ActivityFeedItemTypes["incompletedSoloStreak"] = "incompletedSoloStreak";
    ActivityFeedItemTypes["lostSoloStreak"] = "lostSoloStreak";
    ActivityFeedItemTypes["completedChallengeStreak"] = "completedChallengeStreak";
    ActivityFeedItemTypes["incompletedChallengeStreak"] = "incompletedChallengeStreak";
    ActivityFeedItemTypes["joinedChallenge"] = "joinedChallenge";
    ActivityFeedItemTypes["archivedChallengeStreak"] = "archivedChallengeStreak";
    ActivityFeedItemTypes["restoredChallengeStreak"] = "restoredChallengeStreak";
    ActivityFeedItemTypes["deletedChallengeStreak"] = "deletedChallengeStreak";
    ActivityFeedItemTypes["lostChallengeStreak"] = "lostChallengeStreak";
    ActivityFeedItemTypes["createdTeamStreak"] = "createdTeamStreak";
    ActivityFeedItemTypes["archivedTeamStreak"] = "archivedTeamStreak";
    ActivityFeedItemTypes["restoredTeamStreak"] = "restoredTeamStreak";
    ActivityFeedItemTypes["deletedTeamStreak"] = "deletedTeamStreak";
    ActivityFeedItemTypes["editedTeamStreakName"] = "editedTeamStreakName";
    ActivityFeedItemTypes["editedTeamStreakDescription"] = "editedTeamStreakDescription";
    ActivityFeedItemTypes["completedTeamMemberStreak"] = "completedTeamMemberStreak";
    ActivityFeedItemTypes["incompletedTeamMemberStreak"] = "incompletedTeamMemberStreak";
    ActivityFeedItemTypes["joinedTeamStreak"] = "joinedTeamStreak";
    ActivityFeedItemTypes["lostTeamStreak"] = "lostTeamStreak";
    ActivityFeedItemTypes["createdAccount"] = "createdAccount";
    ActivityFeedItemTypes["followedUser"] = "followedUser";
})(ActivityFeedItemTypes = exports.ActivityFeedItemTypes || (exports.ActivityFeedItemTypes = {}));
exports.default = ActivityFeedItemTypes;
//# sourceMappingURL=ActivityFeedItemTypes.js.map