"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var RouterCategories;
(function (RouterCategories) {
    RouterCategories["agendaJobs"] = "agenda-jobs";
    RouterCategories["feedbacks"] = "feedbacks";
    RouterCategories["users"] = "users";
    RouterCategories["user"] = "user";
    RouterCategories["soloStreaks"] = "solo-streaks";
    RouterCategories["teamStreaks"] = "team-streaks";
    RouterCategories["streakRecommendations"] = "streak-recommendations";
    RouterCategories["completeSoloStreakTasks"] = "complete-solo-streak-tasks";
    RouterCategories["incompleteSoloStreakTasks"] = "incomplete-solo-streak-tasks";
    RouterCategories["completeTeamMemberStreakTasks"] = "complete-team-member-streak-tasks";
    RouterCategories["incompleteTeamMemberStreakTasks"] = "incomplete-team-member-streak-tasks";
    RouterCategories["completeTeamStreaks"] = "complete-team-streak-tasks";
    RouterCategories["incompleteTeamStreaks"] = "incomplete-team-streaks";
    RouterCategories["completeChallengeStreakTasks"] = "complete-challenge-streak-tasks";
    RouterCategories["incompleteChallengeStreakTasks"] = "incomplete-challenge-streak-tasks";
    RouterCategories["test"] = "test";
    RouterCategories["stripe"] = "stripe";
    RouterCategories["followers"] = "followers";
    RouterCategories["streakTrackingEvents"] = "streak-tracking-events";
    RouterCategories["teamMemberStreaks"] = "team-member-streaks";
    RouterCategories["friendRequests"] = "follower-requests";
    RouterCategories["dailyJobs"] = "daily-jobs";
    RouterCategories["emails"] = "emails";
    RouterCategories["profileImages"] = "profile-images";
    RouterCategories["challenges"] = "challenges";
    RouterCategories["challengeStreaks"] = "challenge-streaks";
    RouterCategories["notes"] = "notes";
    RouterCategories["activityFeedItems"] = "activity-feed-items";
    RouterCategories["databaseStats"] = "database-stats";
    RouterCategories["following"] = "following";
    RouterCategories["achievements"] = "achievements";
})(RouterCategories || (RouterCategories = {}));
exports.default = RouterCategories;
//# sourceMappingURL=RouterCategories.js.map