import UserTypes from '../Types/UserTypes';
import { PastSubscription } from './PastSubscription';
import { BasicUser } from './BasicUser';
import { DatabaseAchievementType } from './DatabaseAchievement';
import { ProfileImages } from './ProfileImages';
import { UserPushNotifications } from './UserPushNotifications';
import { PushNotification } from './PushNotification';
import { Onboarding } from './Onboarding';
import { LongestEverSoloStreak } from './LongestEverSoloStreak';
import { LongestEverChallengeStreak } from './LongestEverChallengeStreak';
import { LongestEverTeamMemberStreak } from './LongestEverTeamMemberStreak';
import { LongestEverTeamStreak } from './LongestEverTeamStreak';
import { LongestEverStreak } from './LongestEverStreak';
import { LongestCurrentStreak } from './LongestCurrentStreak';

export interface PopulatedCurrentUser {
    _id: string;
    membershipInformation: {
        isPayingMember: boolean;
        pastMemberships: PastSubscription[];
        currentMembershipStartDate: Date | null;
    };
    userType: UserTypes;
    timezone: string;
    following: BasicUser[];
    followers: BasicUser[];
    totalStreakCompletes: number;
    totalLiveStreaks: number;
    achievements: DatabaseAchievementType[];
    profileImages: ProfileImages;
    hasProfileImageBeenCustomized: boolean;
    pushNotification: PushNotification;
    pushNotifications: UserPushNotifications;
    hasCompletedIntroduction: boolean;
    hasCompletedTutorial: boolean;
    onboarding: Onboarding;
    hasCompletedOnboarding: boolean;
    createdAt: string;
    updatedAt: string;
    temporaryPassword: string;
    username: string;
    hasUsernameBeenCustomized: boolean;
    hasVerifiedEmail: boolean;
    hasCustomPassword: boolean;
    teamStreaksOrder: string[];
    coins: number;
    oidXp: number;
    longestSoloStreak: LongestEverSoloStreak;
    longestChallengeStreak: LongestEverChallengeStreak;
    longestTeamMemberStreak: LongestEverTeamMemberStreak;
    longestTeamStreak: LongestEverTeamStreak;
    longestEverStreak: LongestEverStreak;
    longestCurrentStreak: LongestCurrentStreak;
    email?: string;
    firstName?: string;
    lastName?: string;
    stripe?: {
        customer: string;
        subscription: string;
    };
}
